const dbConfig = require("../config/db.config.js");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.project = require("./projects.db.js")(mongoose)
db.script = require("./scripts.db.js")(mongoose)
module.exports = db;
